### ISSUE TITLE
Sprint 2 goal!

### ISSUE THREAD

**Issue by Okidokie98** [HZ-HBOICT-Y2-2425/uvc-project-backend-team-1-greedy-goblins#26]
Sprint goal:

1. Als een gebruiker wil ik een overzicht hebben van alle locaties in de buurt zodat ik één specefieke locatie kan inzien.
2. Als een gebruiker wil ik producten selecteren zodat ik deze kan bestellen.

Taken:
- Microservice 2 (User + Bestellen)
- Pagina van één bedrijf
- - Voorraad (producten)
- - Adres
- - Beschrijving
- Kaart met alle locaties
- Microservice 3 start (Kaarten + Collectie)

**Comment by FroyoFrozen** [comment]
Niet meer nodig
